version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install --upgrade pip setuptools
  steps:
    - install: pip install -r requirements.txt
    - build: sphinx -T -b html -d _build/doctrees -D language=en docs/ _build/html

sphinx:
  configuration: docs/conf.py
